### PR TITLE
Update corrupted_375.md

### PR DESCRIPTION
**Pull request by neptunia**

### CODE REVIEW

**Comment by LalaNguyen** [comment]
Hello MegaAbsol,

Thank for posting your approach on corrupted. I'm trying to reproduce your approach without success at the part of generating the binary string. What have you done with the different bytes that differ from 0 and 1 ? Simply discarding them doesn't give me the same binary string : (

**Comment by mzhang28** [comment]
Hey LalaNguyen.

The binary string generated represents whether that byte differed between the two images, rather than the numerical difference. A difference between corresponding bytes in the two images is represented by 1, and a lack of difference between corresponding bytes in the two images is represented by 0.

Check out the following script I wrote and its output:
image

Does that make a little bit more sense?

**Comment by LalaNguyen** [comment]
Thank for your support failedxyz ! I understood now, the approach is undoubtedly clear, but I'm still not be able to reproduce your instructions. Here are the steps I took:
1. Firstly, I downloaded the Yuno file from easyctf. yuno-corrupted
2. Secondly, I downloaded the Original Yuno from the writeups as suggested at http://cs623226.vk.me/v623226328/12faa/xLiegfGaFhA.jpg. yuno-original
3. Finally, applying the script above gave me this result
screen shot 2015-11-16 at 12 42 30 pm
Looking forward to seeing your reply,

**Comment by neptunia** [comment]
Hi LaLaNguyen,
sorry, I put the wrong original image :(
when i get home will fix the writeup, i have the original picture there

alternatively michael zhang could send me the link :P

**Comment by LalaNguyen** [comment]
Yeah, I'm curious to know where you got the original picture since there is only one option available out there using Google picks. : D
Thank in advance !

**Pull request merged**
